baseURL = "https://tastycpp.com/"
languageCode = 'en-us'
title = 'Tasty C++'

disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = 'Website about C++'

[params.author]
  name = "Oleksandr Gituliar"
  email = "oleksandr@gituliar.net"

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'manni'
